theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


title: "Deque"
author: "Quentin Duval"
description: "Functions In, Fictions Out"

# How to join me
twitter_username: "quduval"
github_username: "QuentinDuval"
linkedin_username: "quentin-duval-53ba6576"
#email: "mymail@box.com"

# URL
# url: "http://deque.net"
baseurl: # the subpath of your site, e.g. "/blog"
repository: "QuentinDuval/quentinduval.github.io"
comments_repo: QuentinDuval/quentinduval.github.io

google_analytics: G-RRHHYN266B
rss: rss

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

titles_from_headings:
  strip_title: true
  collections: true

# permalink: /:categories/:year/:month/:day/:title:output_ext
permalink: /:year/:month/:day/:title:output_ext

show_excerpts: true
paginate: 8

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
