encoding: UTF-8

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


title: "Deque"
author: "Quentin Duval"
description: "Functions In, Fictions Out"


# URL
# url: "http://deque.net"
baseurl: # the subpath of your site, e.g. "/blog"
repository: "QuentinDuval/quentinduval.github.io"
comments_repo: QuentinDuval/quentinduval.github.io

analytics:
  provider: "google"
  google:
    tracking_id: "G-RRHHYN266B"
    anonymize_ip: true

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    disable: true

search: true
search_full_content: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

titles_from_headings:
  strip_title: true
  collections: true

# permalink: /:categories/:year/:month/:day/:title:output_ext
permalink: /:year/:month/:day/:title:output_ext

show_excerpts: true
paginate: 6

include:
  - _pages

comments:
  provider: "disqus"
  disqus:
    # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
    shortname: "https-quentinduval-github-io"

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other

twitter:
  username: "quduval"

author:
  # name   : "Quentin Duval"
  # avatar : "/assets/images/rg.jpg"
  bio    : >-
    My name is Quentin.

    I am a software engineer since 2010, and currently a research engineer in the field of AI since 2020.
    You can read more about me in the [About me](/about-me/) section.
  location: "Montreal, Quebec"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: https://scholar.google.com/citations?user=XTaVGqYAAAAJ
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/QuentinDuval"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/quduval"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/quentin-duval-53ba6576"


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/QuentinDuval"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/quduval"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/quentin-duval-53ba6576/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: "Quentin Duval"
      layout: post
      read_time: false
      comments: true
      share: true
      related: true
      # classes: wide
      toc: true
      toc_label: Table of content
      show_date: true
      share_light: true
      sidebar:
        title: ""
        # nav: sidebar-post
        recent_posts: true
        categories: true
        contact_info: true
      author_profile: false
